variable "boot_command" {}
variable "boot_wait" {}
variable "disk_size" {}
variable "format" {}
variable "headless" {}
variable "http_port_max" {}
variable "http_port_min" {}
variable "iso_checksum" {}
variable "iso_url" {}
variable "output_directory" {}
variable "qemuargs" {}
variable "shutdown_command" {}
variable "skip_compaction" {}
variable "disk_compression" {}
variable "ssh_password" {}
variable "ssh_username" {}
variable "ssh_wait_timeout" {}
variable "vm_name" {}
variable "net_device" {}
variable "disk_interface" {}
