variable "disk_compression" {}
variable "disk_interface" {}
variable "disk_size" {}
variable "floppy_dirs" {}
variable "floppy_files" {}
variable "format" {}
variable "headless" {}
variable "http_port_max" {}
variable "http_port_min" {}
variable "iso_checksum" {}
variable "iso_url" {}
variable "net_device" {}
variable "output_directory" {}
variable "qemuargs" {}
variable "shutdown_command" {}
variable "skip_compaction" {}
variable "vm_name" {}
variable "winrm_password" {}
variable "winrm_timeout" {}
variable "winrm_username" {}
